### ISSUE TITLE
Activity bar is not being themed in 12.0 update

### ISSUE THREAD

**Issue by smlombardi** [pouyakary/ProColors#10]
Was excited to see the new update take advantage of the new VSCode workbench theming.  Unfortunately, my activity bar is not being themed like your screenshot.

<img width="699" alt="screen shot 2017-05-14 at 12 25 00 pm" src="https://cloud.githubusercontent.com/assets/835148/26035814/9ffea8f6-38a0-11e7-92e5-fc1f76b3766d.png">

It seems like the download is not updated?

**Comment by smlombardi** [comment]
I see now the caveat.  Sorry.

I am going to fork the light theme and make it with the new json format.

**Comment by pouyakary** [comment]
:D the problem is with the format. Because the light them is in `tmTheme` and for that, you need fully JSON theme

**Comment by smlombardi** [comment]
Yes, I already moved it to json format.

**Comment by pouyakary** [comment]
@smlombardi that's so cool, I guess I have to borrow the tmTheme  to JSON converter that you have and build the generator on top of it

**Comment by smlombardi** [comment]
You can set things up the way you want and then choose Develop > Export current settings as theme
