### ISSUE TITLE
minimap in kary-light

### ISSUE THREAD

**Issue by transtone** [pouyakary/ProColors#15]
drag minimap use a ugly orange block is very unhappy.
could you please set it as good as kary-dark?

**Comment by pouyakary** [comment]
Hello @transtone. Again thanks a lot for using this theme and filling issues!

Ah this is a bad one. I'll be filling an issue on vscode for the problem and temporally remove colors of scroll bar in the next update. Thanks a lot for pointing it out 👍

**Comment by pouyakary** [comment]
As promised the scrollbar colors were removed and now that transparent colors are available a truly redesigned ruler is here for you to use. All the ruler colors as well as the scrollbar colors are redefined. I hope you like it (Also can you see how much this image is like contemporary art? :D)

<img width="241" alt="screen shot 2017-10-22 at 8 52 34 pm" src="https://user-images.githubusercontent.com/2157285/31910574-ca1044ea-b84a-11e7-889d-58d3d2bc4f70.png">

And the mini map:

<img width="206" alt="screen shot 2017-10-23 at 11 39 30 pm" src="https://user-images.githubusercontent.com/2157285/31910786-79342a72-b84b-11e7-9f8e-523a67b41edd.png">
