### ISSUE TITLE
Appreciation ❤️

### ISSUE THREAD

**Issue by jiayihu** [pouyakary/ProColors#17]
No bugs here sorry! Just wanted to say thanks for your hard work!

I love light themes but unfortunately they are very rare compared to dark themes and most of them are not pleasant and accessible like yours. You did a really good job! 🔥

**Comment by pouyakary** [comment]
@jiayihu today I was really low and suddenly found this issue; I can't explain how much it meant to me. Your very kind words really made my day and changed my mood. thank you very much for that and I'm really happy that you like the themes. Me too [had the same problem with themes and programming tools](http://kary.us/2017/05/16/my-journey-to-clean-code/) and I'm glad that at some level my solution helped you too.

**Comment by jiayihu** [comment]
I'm happily using your theme for about ~6months, so I really appreciate the effort you put into it. Anyway if you happen to be low take some time for yourself!

**Comment by NlightNFotis** [comment]
@pmkary  For what it's worth, I also want to state my happiness with the work done on this theme. It's awesome, keep it up. My favourite theme thus far, and part of why I have switched to vscode. Also appreciate the work you did on racket support.

**Comment by pouyakary** [comment]
@NlightNFotis &bullet; I though a long time how to respond, but truth is I have no idea! Your very kind words made my day&mdash;just like how @jiayihu did&mdash;there are days when I'm lost, or I feel what I do doesn't matter, and there's always very kinds words like yours that make me happy, bring meaning to what I do, and makes it worth doing. So thank you so much ❤️
