### ISSUE TITLE
Highlighted phrases not visible when searching

### ISSUE THREAD

**Issue by moskal91** [pouyakary/ProColors#20]
Using Kary Dark and Kary Minimal Dark theme, search results are barely visible:
![image](https://user-images.githubusercontent.com/9036050/31305648-f7edcf2c-ab3e-11e7-8f17-5bc1aae3274c.png)

Using default Dark+ theme, the same scenario looks like this:
![image](https://user-images.githubusercontent.com/9036050/31305637-d157b440-ab3e-11e7-919a-c1b0b6ede9ff.png)

It is hard to find search results in long lines of code because of this issue.

**Comment by pouyakary** [comment]
Yeah you're right... Thanks a lot for this issue, I'll fix it in the next version.

**Comment by pouyakary** [comment]
So many improvements regarding of highlights happened. I really hope you like it. This is a preview before the actual version so hint me if you don't like it:

## Search Highlights

<img width="617" alt="screen shot 2017-10-22 at 6 13 37 pm" src="https://user-images.githubusercontent.com/2157285/31910364-1f009af0-b84a-11e7-89b8-0dc17e8ec9c5.png">
<img width="673" alt="screen shot 2017-10-22 at 6 17 18 pm" src="https://user-images.githubusercontent.com/2157285/31910367-209038da-b84a-11e7-980d-8747c88301ac.png">

## Word Highlights

<img width="716" alt="screen shot 2017-10-23 at 3 05 35 pm" src="https://user-images.githubusercontent.com/2157285/31910374-2678c2da-b84a-11e7-9d77-ec2bf3dbbbba.png">
<img width="656" alt="screen shot 2017-10-23 at 12 05 11 am" src="https://user-images.githubusercontent.com/2157285/31910383-2c7230c2-b84a-11e7-91d4-302ec5a6ef90.png">

**Comment by moskal91** [comment]
Looks very nice and does the job for me, thanks for looking into it!
