### ISSUE TITLE
Suggestion: Background of the selected node from the Explorer panel's tree items should be the same even when lost focus

### ISSUE THREAD

**Issue by takato1314** [pouyakary/ProColors#21]
Hello, I have one more feedback that i notice when i was working with this VSCode theme.

This is the initial state of the **selected** tree node from the Explorer panel tree items 
<img width="214" alt="2017-10-22_15-28-20" src="https://user-images.githubusercontent.com/10910968/31859415-760406d2-b73e-11e7-94f9-4386e12235a2.png">

But it seems that the color will change to somewhat not visible when it loses focus from the explorer panel (Eg. while typing code in the editor) as shown below. (ps: I have marked the difference between selected node and hover node when editor is still in focused.)
<img width="265" alt="2017-10-22_15-26-33" src="https://user-images.githubusercontent.com/10910968/31859441-c0d24660-b73e-11e7-86a6-af03490d973d.png">

IMO, i think that the same color scheme for selected should be maintained in explorer even when it has lost focus, because imagine you're working with multiple partial project files, it might be useful to get to know where you are in your tree directory. VSCode team has made a good job to automatically set the  selected tree node according to your current selected tab on top, i just feel that it might be better if the selected color will be the same as it is when it's active.

Thanks.
(ps: The icons in the tree items are from VSCode icons (https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons) just in case you're wondering).

**Comment by pouyakary** [comment]
fixed... :D

<img width="386" alt="screen shot 2017-10-24 at 12 20 11 am" src="https://user-images.githubusercontent.com/2157285/31912551-2143b0f2-b851-11e7-9b04-e2cc7e9b0483.png">
