### ISSUE TITLE
Border around hover widget?

### ISSUE THREAD

**Issue by nilshartmann** [pouyakary/ProColors#22]
Hi,

first let me say that I really, really like your Lite theme! 💛 I'm using in in VS Code.

There is only a minor thing that bothers me from time to time: It's sometimes hard to recognize the hover widget as a hover widget. The first time I saw it, i thought its a rendering bug:

![image](https://user-images.githubusercontent.com/435073/34436160-524bb520-ec93-11e7-8f8c-b7aebec85266.png)

I think it would be better I there were at least a thin border around and/or a slightly different background color. For Example:

![image](https://user-images.githubusercontent.com/435073/34436157-4499f7a2-ec93-11e7-8128-0d6d5eb3ebc8.png)

What do you think?

**Comment by pouyakary** [comment]
Hi Nils. So happy that you're using the theme! I'm very sorry about the bad border colors there. I actually can't spot them on my own machine.

<img width="654" alt="screen shot 2017-12-29 at 3 56 58 pm" src="https://user-images.githubusercontent.com/2157285/34437170-47fbfc4c-ecb1-11e7-8007-ec51b1bf59bc.png">

But I agree the border colors are in a really bad contrast.

In the next version I'll make sure you get a right border :D

**Comment by nilshartmann** [comment]
Hi,

thanks for coming back so quickly!

Just realized the border/color for the in-place editing widget (i.e. rename symbol):

![image](https://user-images.githubusercontent.com/435073/34438285-f81161be-eca5-11e7-9728-b0308df0ba51.png)

Here it looks very good!

Thanks again!

**Comment by pouyakary** [comment]
You're welcome :)
