### ISSUE TITLE
Typo in VS marketplace Readme

### ISSUE THREAD

**Issue by khaled-nuur** [pouyakary/ProColors#25]
its simple.. here is a shot
![capture](https://user-images.githubusercontent.com/28248852/45373585-77ba1200-b5f8-11e8-9bc8-d52bf4778216.PNG)
just change **PEG** to **PUG**
i would make pull req. but  I didn't found this file in the repo(not searched well)
looking forward 😄

**Comment by pouyakary** [comment]
Hi @khaled-nuur! Thanks for helping! It's actually [PEG.js](https://pegjs.org/). A short for "Parsing Expression Grammar" which are is form of language grammar. So everything is right, don't you worry!

Thanks a lot for caring and helping
Hope you have a great time!
Pouya
