### ISSUE TITLE
Low contrast for comments and selection (light themes)

### ISSUE THREAD

**Issue by kleinfreund** [pouyakary/ProColors#26]
The contrast of comments’ foreground color to the background of both light variations of the theme is way too low. I can barely read the text.

![screenshot from 2018-10-16 13-38-34](https://user-images.githubusercontent.com/5774638/47013835-cce1ca00-d148-11e8-9497-b8389ba16c54.png)

Similarly, the background color of selections is too low. In the below screenshot, `addShortcode` is selected.

![screenshot from 2018-10-16 13-41-13](https://user-images.githubusercontent.com/5774638/47013969-2d710700-d149-11e8-9a36-b8b055249d2e.png)

Any chance the colors are going to be changed?

**Comment by pouyakary** [comment]
@kleinfreund that is new to be honest. I use Hasklig medium weight and so I couldn't see it. I will add this to the stuff that needs to be fixed.
