### ISSUE TITLE
Nice to have ProColors theme for Intellij IDEA

### ISSUE THREAD

**Issue by mxmind** [pouyakary/ProColors#30]
The excellent theme would be great to have this theme for IntelliJ IDEA

**Comment by pouyakary** [comment]
@mxmind thanks a lot for that! I designed the theme with a base to run on any editor. the [themeX](https://github.com/pmkary/themeX) project was designed for that. But then what happened was the theme got sophisticated in terms of supporting rich tokens and grammars. for now no editor but vscode/sublime-text/atom has a tokenizing engine as rich and therefore no editor but these can support the theme (at least they don't colorize that pretty) so I don't know, it seems for now we're stuck with only vscode
