### ISSUE TITLE
Background color mismatch in Kary Pro Colors - Minimal Dark

### ISSUE THREAD

**Issue by hexpunk** [pouyakary/ProColors#31]
I've noticed that two areas of the background color of the editor are mismatched in the "Kary Pro Colors - Minimal Dark" theme.

I'm running VSCode Version 1.35.0 on MacOS Mojave 10.14.5 (18F132).

I'm attaching two screenshots.
![bgcolor_mismatch](https://user-images.githubusercontent.com/10983817/59217613-f215c380-8b83-11e9-9127-0bdea2f589c8.png)
This first one has only been manipulated to hide the code as it is my employer's.  (Sorry about that.)

![exaggerated](https://user-images.githubusercontent.com/10983817/59217619-f5a94a80-8b83-11e9-80b1-9eb8549778c8.png)
This second screenshot is the same as the first one, but to exaggerate the effect (since the original can be difficult to spot the difference) I've gone into The Gimp and used the flood fill tool with a threshold of 0 to fill the two different colors in red and blue to make the borders more obvious.

**Comment by pouyakary** [comment]
@JayAndCatchFire hey there! thanks for using Pro Colors 💪 

This is a [visual studio code issue (48043)](https://github.com/microsoft/vscode/issues/48043). You may reopen the issue there :D

**Comment by hexpunk** [comment]
Thanks for the tip.  I was able to adjust my color profile in MacOS and it seems to have solved the problem.  Weird that such a setting can affect software in such a way.

**Comment by pouyakary** [comment]
@JayAndCatchFire happy to help :D and yeah! strange stuff!
