### ISSUE TITLE
Dart lang support

### ISSUE THREAD

**Issue by theiskaa** [pouyakary/ProColors#33]
Thanks for the awesome theme! But I can't see here support for dart/flutter, it would better if you add.

**Comment by pouyakary** [comment]
Hey how are you? Can you do me a favor? Give me a huge chunk of code that contains everything dart has. Then I can find a good color and apply to it

**Comment by theiskaa** [comment]
I'm quite good man thanks. Okay sure thing, I'll do soon as I can as possible

**Comment by theiskaa** [comment]
Very basic dart/flutter code:
Also you can try it online by following: https://dartpad.dev/flutter?null_safety=true
```dart
import 'package:flutter/material.dart';

// Basic flutter app
final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('Hello, World!', style: Theme.of(context).textTheme.headline4);
  }
}
```

**Comment by pouyakary** [comment]
@theiskaa thanks but it's not enough.
The idea of good token coverage is to have every possible token that the language has.
Are you sure that these are every possible thing? 

To me [this](https://learnxinyminutes.com/docs/dart/) comes to mind, but I'm not sure if it fully covers the language.

**Comment by theiskaa** [comment]
@pouyakary ya man, what are you put I think enough.

**Comment by pouyakary** [comment]
@theiskaa So I worked on the Dart support for the past two days and, while on my side I wanted a better Dart experience, the grammar itself was not good enough. So I worked on the grammar (and actually a lot), here is the result of it:

https://github.com/Dart-Code/Dart-Code/pull/4067

You can have a preview of it, I'll ship the next Pro Colors version as soon as the upstream branch accepts the patch and release. Till then, you can give it an upvote :)
