### ISSUE TITLE
Support for `editor.bracketPairColorization`

### ISSUE THREAD

**Issue by furudean** [pouyakary/ProColors#34]
In Visual Studio Code 1.60, [a new option has been added to support bracket pair colorization in the editor](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization). Bracket pair colorization [is themable](https://code.visualstudio.com/api/references/theme-color#editor-colors) (see `editorBracketHighlight`, etc), meaning this extension could provide its own bracket pair colors!

By default it looks like this, some rather garish color choices by the VSCode team.

![Screen Shot 2021-09-02 at 12 53 23 PM](https://user-images.githubusercontent.com/31383109/131900457-6f0f0318-6297-4690-9fde-59cf4bd1cf7c.png)

Would be awesome if this could be added, thanks!

**Comment by pouyakary** [comment]
How interesting! Adding this to the theme will totally damage the harmony so I have to do lots of playing with it to see what colors actually are nice. But I will definitely try!

**Comment by pouyakary** [comment]
I have added some colors but I'll keep the issue open because I'm still not satisfied :)
