### ISSUE TITLE
How to change ruby comment text color?

### ISSUE THREAD

**Issue by vfonic** [pouyakary/ProColors#36]
Hi Puuya!

I'm having similar issue like this one here [Low contrast for comments and selection (light themes) #26](https://github.com/pouyakary/ProColors/issues/26)

I'm trying to override the comment color, but to no avail.

I've found this helpful comment, but still no luck:
https://github.com/pouyakary/ProColors/issues/23#issuecomment-376505517

Here's what the popup says when I do: "> Developer: Inspect Editor Tokens and Scopes":
<img width="559" alt="Screen Shot 2021-12-02 at 12 33 51" src="https://user-images.githubusercontent.com/67437/144414483-be5183ea-4ead-449d-87c8-4ca65a69d985.png">

I tried many different combinations, but nothing works:

```js
"workbench.colorCustomizations": {
    "[Kary Pro Colors － Eye Light]": {
      "comment.line.number-sign.ruby": "#ff0000"
    }
  }

"editor.tokenColorCustomizations": {
    "[Kary Pro Colors － Light]": {
      "comments": "#FF0000"
    }
  }
```

Any suggestions?

Thanks!

**Comment by pouyakary** [comment]
@vfonic hey! thanks for using Pro Colors :)

I think what you're looking for is `editor.tokenColorCustomizations`, there you can change these colors.

**Comment by vfonic** [comment]
Holy s**t! Now it works! 🤷‍♂️
Thanks!

Here's the working setting for referrence:

```json
"editor.tokenColorCustomizations": {
    "[Kary Pro Colors － Eye Light]": {
      "comments": "#FF0000"
    }
  }
```

**Comment by pouyakary** [comment]
@vfonic haha! Awesome. I have zero idea what is a good "good contrast" color for the theme so if you ever found a working color tell me, maybe it made it way to eye light.

**Comment by vfonic** [comment]
I just made the color slightly darker gray:

```json
  "editor.tokenColorCustomizations": {
    "[Kary Pro Colors － Eye Light]": {
      "comments": "#aaa"
    }
  }
```
