### ISSUE TITLE
"Default" color same as comments

### ISSUE THREAD

**Issue by haudan** [pouyakary/ProColors#40]
Unknown tokens are colored (effectively) the same as comments. This makes readability difficult, since code can easiliy be mistaken for comments.

Request: Independent from first class language support, non-comments should be better distuingishable from comments.

![image](https://github.com/pouyakary/ProColors/assets/3426722/d391448f-6704-4aa5-902b-1987561b4c85)
![image](https://github.com/pouyakary/ProColors/assets/3426722/2d84d626-ce26-4c0c-a447-d9f556d911b5)

**Comment by pouyakary** [comment]
@Lisoph hi! sorry for the inconvenience this updated have caused on you. I have released a new version (34.2) which should have fixed this. I hope you like the new foreground colors. This version was a really though decision and I appreciate the feedback you provided. Have a nice weekend!

**Comment by haudan** [comment]
Awesome, thanks for the quick fix!
