### ISSUE TITLE
Question: Is it possible to consider variable scope for colours?

### ISSUE THREAD

**Issue by sladiri** [pouyakary/ProColors#6]
Thank you for the nice theme. I am not sure, if this is possible, here is an example:
```js
function f (x) {
  return function g(y) {
    // Ideally, x and y would be coloured according to the function scope, they are declared in :)
    return x + y  
  }
}
```

**Comment by pmkary** [comment]
Dear @sladiri: Hi! Thanks a lot for asking this and for using our theme :los

**Comment by pouyakary** [comment]
Dear @sladiri hi! Thanks a lot for asking this and for using our theme ❤️ 

In some editors such and Emacs and Vim themes are defined using a script that parses and colorizes the theme, in those themes it's possible to have things colored with their scopes (such as parentheses pairs in Lisp languages.). However VSCode uses a format called `tmTheme`. Sadly this format only specifies the resulting tokens generated by the editor which lacks any programming tooling. So if you look:

<img width="598" alt="screen shot 2016-12-18 at 7 45 35 am" src="https://cloud.githubusercontent.com/assets/2157285/21291474/0a854294-c4f6-11e6-87c8-a3741d417daf.png">


<img width="638" alt="screen shot 2016-12-18 at 7 45 51 am" src="https://cloud.githubusercontent.com/assets/2157285/21291475/0ac3ec88-c4f6-11e6-85b0-72bea6fb3261.png">

It's not possible to distinguish the branch/scope level in the themes.
