### ISSUE TITLE
Support Sass highlighting better

### ISSUE THREAD

**Issue by daveredfern** [pouyakary/ProColors#7]
Hi,

First off, great theme!

It would be nice if Scss files had better highlighting. See this demo below where one is selected as Sass language mode and the other is CSS.

Sass:
![image](https://cloud.githubusercontent.com/assets/183473/22502339/59e5df88-e864-11e6-9306-f2308adada72.png)

CSS:
![image](https://cloud.githubusercontent.com/assets/183473/22502358/6969cc76-e864-11e6-9776-80abaf20ec40.png)

I don't think either are necessarily correct for Sass but the CSS one seems a better direction with more colour to differentiate parts.

Thanks,
Dave.

**Comment by pouyakary** [comment]
@daveredfern hi!
Thanks a lot for using our theme! And thanks a lot for your kind words. I personally would love to have that implemented however I'm not a SCSS coder (if you look you see for example LESS has a great support in the theme) so if you send me a code snippet that has all of the features you know I can easily tokenize the code and have them implemented in the theme.

**Comment by daveredfern** [comment]
@pmkary I will have a tinker over the next few days to come up with something :)

**Comment by pouyakary** [comment]
@daveredfern that would be awesome 👍

**Comment by pouyakary** [comment]
`Duplicate` of #5 but okay
