### ISSUE TITLE
Implement workbench theming from VS Code 1.12

### ISSUE THREAD

**Issue by coastermcgee** [pouyakary/ProColors#9]
Now that VS Code supports [workbench theming](https://code.visualstudio.com/updates/v1_12#_workbench-theming), would it be possible to update the Kary Foundation themes to incorporate this feature.  I've done something quick and dirty for the light theme as an example but it would be awesome to have something officially implemented in a future update!

```
"workbench.colorCustomizations": {
    "activityBar.background": "#f7f7f7",
    "activityBar.foreground": "#bdbdbd",
    "activityBarBadge.background": "#c94824",
    "activityBarBadge.foreground": "#f7f7f7",
    "button.background": "#985da3",
    "button.foreground": "#f7f7f7",
    "contrastBorder": "#e5e5e5",
    "editorLineNumber.foreground": "#ccc",
    "list.activeSelectionBackground": "#f2f2f2",
    "list.activeSelectionForeground": "#428226",
    "list.hoverBackground": "#f2f2f2",
    "list.inactiveSelectionBackground": "#f2f2f2",
    "notification.background": "#00945e",
    "notification.foreground": "#f7f7f7",
    "panelTitle.activeBorder": "#a56416",
    "panelTitle.activeForeground": "#a56416",
    "panelTitle.inactiveForeground": "#bdbdbd",
    "sideBar.background": "#f7f7f7",
    "sideBarSectionHeader.background": "#f7f7f7",
    "sideBarTitle.foreground": "#9b9b9b",
    "statusBar.background": "#f7f7f7",
    "statusBar.debuggingBackground": "#c94824",
    "statusBar.foreground": "#ccc",
    "statusBar.noFolderBackground": "#f7f7f7",
    "tab.activeBackground": "#fff9ed",
    "tab.activeForeground": "#a56416",
    "tab.inactiveBackground": "#f7f7f7",
    "tab.inactiveForeground": "#bdbdbd",
    "titleBar.activeBackground": "#f7f7f7",
    "titleBar.activeForeground": "#6c6c6c"
}
```

**Comment by pouyakary** [comment]
@coastermcgee 

Wow, nice!! When I made the theme I never thought it'll ever get this kind of attention. Thank you so much. I already have a prototype that I'm working on:

<img width="1187" alt="screen shot 2017-05-05 at 9 48 54 pm" src="https://cloud.githubusercontent.com/assets/2157285/25756673/de965188-31dc-11e7-8ede-192980fd88d2.png">

```json
{
    "workbench.colorCustomizations": {
        "contrastBorder": "#e5e5e5",
        "peekViewEditor.background": "#E2EEFA",
        "peekViewResult.background": "#E2EEFA",
        "focusBorder": "#3778B7",
        "widget.shadow": "#cccccc",
        "editorGroup.border": "#E0E0E0",
        "editorGroupHeader.noTabsBackground": "#f1f1f1",
        "editorGroup.dropBackground": "#f1f1f1",
        "editorGroupHeader.tabsBackground": "#f1f1f1",
        "tab.inactiveBackground": "#f1f1f1",
        "tab.inactiveForeground": "#aaaaaa",
        "tab.activeForeground": "#C94824",
        "tab.border": "#f1f1f1",
        "editorWidget.background": "#f7f7f7",
        "panelTitle.activeBorder": "#B052A1",
        "titleBar.activeBackground": "#f1f1f1",
        "button.background": "#3778B7",
        "input.background": "#ffffff",
        "input.border": "#ffffff",
        "editorLineNumber.foreground": "#cccccc",
        "scrollbarSlider.background": "#DC8564",
        "scrollbarSlider.activeBackground": "#C94824",
        "scrollbarSlider.hoverBackground": "#C94824",
        "list.activeSelectionBackground": "#E2EEFA",
        "list.activeSelectionForeground": "#3778B7",
        "list.focusBackground": "#E2EEFF",
        "list.inactiveSelectionBackground": "#E2EEFA",
        "list.highlightForeground": "#3778B7",
        "inputOption.activeBorder": "#C94824",
        "activityBar.background": "#f1f1f1",
        "activityBar.foreground": "#aaaaaa",
        "activityBarBadge.background": "#C94824",
        "statusBar.background": "#3778B7",
        "statusBar.noFolderBackground": "#B052A1",
        "statusBar.debuggingBackground": "#C94824",
        "sideBarSectionHeader.background": "#f7f7f7",
        "sideBarTitle.foreground": "#A56416",
        "sideBar.background": "#f1f1f1"
    }
}
```

The problem here is our compiler [themeX](github.com/karyfoundation/themeX). When I wrote it I thought we're going to support standard themes and now we have this extended tmTheme format in JSON which is not the format that the themes are being built on. You have to wait a bit so that I complete a new adaptor for themeX to support this and then it'll be shipped with the themes.

Thanks a lot for your contribution to this theme. It's highly appreciated 👍 

Hope to have the release soon

**Comment by pouyakary** [comment]
@coastermcgee 

I'm glad to announce that workbench theming is implemented. Thanks to dear Benjamin, even the [issue on borders](https://github.com/Microsoft/vscode/issues/26113) is fixed and you can have a look at how it's going to look:

<img width="1280" alt="screen shot 2017-05-28 at 11 58 15 am" src="https://cloud.githubusercontent.com/assets/2157285/26527457/bd114da4-43a9-11e7-85a6-d81e6324d322.png">

Good news is that we now have workbench theming on entire dark-theme:

<img width="1280" alt="screen shot 2017-05-28 at 11 57 38 am" src="https://cloud.githubusercontent.com/assets/2157285/26527456/bc8d53c8-43a9-11e7-8fa7-af0505ec7e44.png">

These are only prototype looks and they are not the final look. But I hope you'll like them and no longer have to use custom theme settings. Thanks a lot for using this theme :D
